spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: mp_user
    password: mp_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

server:
  port: 8080